### ISSUE TITLE
Validate date values

### ISSUE THREAD

**Issue by meyeran** [bus-factor/ares#58]
As a user I want to validate date values.

- custom format (Y-m-d | Y.m.d | Y.m) validation
- date1 gt/lt/eq date2

**Comment by bus-factor** [comment]
Is this request only about formatted date strings, e.g. ```'2019-03-20'``` or also about ```DateTime``` objects? The latter one should be dealt with in a separate issue.

Date strings could be handled via a date validation rule:
```
$schema = [
    'type' => 'string',
    'date' => [
        'format' => 'Y-m-d',
        'between' => [..., ...],
        'after' => '...',
        'before' => '...',
    ],
];
```

The second requirement is about cross field validation and should also be handled as a separate issue.
