### ISSUE TITLE
Validation by enum (IN) values

### ISSUE THREAD

**Issue by meyeran** [bus-factor/ares#59]
As a user I want to validate by enum values like this:

`
$schema = [
    'type' => 'string',
    'string' => [
        'in' => ['sandbox', 'production'],
    ],
];
`

**'in' => sandbox, production**
The value must be included in the given list of values.

**'not_in' => 'admin'**
The value must not be included in the given list of values.

**Comment by bus-factor** [comment]
Implemented a 'allowed' validation rule for now. Have a look at README.md:
```php
$schema = [
    'type' => 'string',
    'allowed' => ['CD', 'DVD', 'Magazine', 'Book'],
];
```
A 'forbidden' validation rule will be implemented as a separate feature.
